application: trailofclues
version: 1
runtime: python27
api_version: 1

handlers:
- url: /.*
  script: main.py
  
- url: /static
  static_dir: static

threadsafe:
- yes

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on
